name: travel_booking_app
description: A Flutter app for booking flights and hotels with a modern UI.
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5 # لإجراء طلبات HTTP
  provider: ^6.0.2 # لإدارة الحالة (State Management)
  shared_preferences: ^2.5.3 # لتخزين البيانات محليًا
  intl: ^0.18.1 # لتنسيق التاريخ والوقت
  image_picker: ^0.8.7 # لاختيار الصور
  cupertino_icons: ^1.0.2 # أيقونات iOS
  google_fonts: ^3.0.1 # خطوط Google
  fluttertoast: ^8.2.1 # إشعارات toast
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
